# Generated by Django 3.2.7 on 2021-10-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alternativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(blank=True)),
                ('b', models.TextField(blank=True)),
                ('c', models.TextField(blank=True)),
                ('d', models.TextField(blank=True)),
                ('e', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vestibular', models.CharField(blank=True, max_length=255)),
                ('banca', models.CharField(blank=True, max_length=255)),
                ('texto', models.TextField()),
                ('alternativa_certa', models.CharField(max_length=1)),
                ('alterativas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.alternativas')),
            ],
        ),
    ]
