# Generated by Django 3.2.7 on 2021-10-05 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alternativas_perguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vestibular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.banca'),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='vestibular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.vestibular'),
        ),
    ]
